version: '3.7'

services:
  mysql:
    image: mysql:8
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=desafio-docker-compose-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - docker-compose-network

  api-docker-compose:
    build:
      context: .
    container_name: api-docker-compose
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - docker-compose-network

networks:
  docker-compose-network:
    name: docker-compose-network
    external: true
    driver: bridge

volumes:
  db: