name: CI

on: 
  push:
    branches: 
      - main

jobs: 
  build:
    name : 'Build and Push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]

    steps: 
      - uses: actions/checkout@v4.1.7
      
      - name: Setup node | ${{ matrix.node }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn
            
            