name: CI

on: 
  push:
    branches: 
      - main

jobs: 
  build:
    name : 'Build and Push'
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4.1.7
      
      - name: Setup node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn
            
            