name: CI

on: 
  push:
    branches: 
      - main

jobs: 
  build:
    name : 'Build and Push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]

    steps: 
      - uses: actions/checkout@v4.1.7
      
      - name: Setup node | ${{ matrix.node }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn

      - name: Generate tag
        id: generate_tag 
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: docker build -t paulacristinamartins/docker-compose-ci-api:${{ steps.generate_tag.outputs.sha }} . 

      - name: Push image
        run: docker push paulacristinamartins/docker-compose-ci-api:${{ steps.generate_tag.outputs.sha }} . 
            
            